/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesRecentRouteImport } from './routes/pages/recent'
import { Route as PagesFavoriteRouteImport } from './routes/pages/favorite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRecentRoute = PagesRecentRouteImport.update({
  id: '/pages/recent',
  path: '/pages/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesFavoriteRoute = PagesFavoriteRouteImport.update({
  id: '/pages/favorite',
  path: '/pages/favorite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pages/favorite': typeof PagesFavoriteRoute
  '/pages/recent': typeof PagesRecentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages/favorite': typeof PagesFavoriteRoute
  '/pages/recent': typeof PagesRecentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pages/favorite': typeof PagesFavoriteRoute
  '/pages/recent': typeof PagesRecentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pages/favorite' | '/pages/recent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pages/favorite' | '/pages/recent'
  id: '__root__' | '/' | '/pages/favorite' | '/pages/recent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesFavoriteRoute: typeof PagesFavoriteRoute
  PagesRecentRoute: typeof PagesRecentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/recent': {
      id: '/pages/recent'
      path: '/pages/recent'
      fullPath: '/pages/recent'
      preLoaderRoute: typeof PagesRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/favorite': {
      id: '/pages/favorite'
      path: '/pages/favorite'
      fullPath: '/pages/favorite'
      preLoaderRoute: typeof PagesFavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesFavoriteRoute: PagesFavoriteRoute,
  PagesRecentRoute: PagesRecentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
